---
- name: make sure user for Elasticsearch exists
  user:
    name: "{{ elasticsearch_user }}"

- name: unarchive elasticsearch
  unarchive:
    remote_src: yes
    dest: "{{ elasticsearch_install_dir | dirname }}"
    src: "{{ elasticsearch_url }}"
    creates: "{{ elasticsearch_install_dir }}/bin/elasticsearch"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"

- name: create required data directory
  file:
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    path: "{{ elasticsearch_path_data }}"

- name: create required log directory
  file:
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    path: "{{ elasticsearch_path_logs }}"

- name: create configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ elasticsearch_install_dir }}/config/{{ item }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
  with_items:
    - elasticsearch.yml
    - jvm.options
    - log4j2.properties
  notify: restart elasticsearch

- name: fix permissions in config dir
  file:
    path: "{{ elasticsearch_install_dir }}/config/"
    recurse: yes
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"

- name: install mandatory plugins
  shell: "cd {{ elasticsearch_install_dir }} && bin/{{ plugin_executable }} install -b {{ item }}"
  with_items: "{{ elasticsearch_plugins }}"
  args:
    creates: "{{ elasticsearch_install_dir }}/plugins/{{ item }}"

- name: fix permissions in plugins dir
  file:
    path: "{{ elasticsearch_install_dir }}/plugins/"
    recurse: yes
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
  when:  elasticsearch_plugins != []

- name: create systemd script
  template:
    src: elasticsearch.service.j2
    dest: /etc/systemd/system/elasticsearch.service
  notify:
    - reload systemd
    - restart elasticsearch

- name: make sure elasticsearch is started
  service:
    name: elasticsearch
    state: started
    enabled: yes
